apiVersion: v1
kind: Service
metadata:
  name: reversi-app
spec:
  selector:
    app: reversi-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30123
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reversi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reversi-app
  template:
    metadata:
      labels:
        app: reversi-app
    spec:
      containers:
      - name: reversi-app
        image: dotnsf/reversi-app
        env:
        - name: DATABASE_URL
          value: "postgres://dbserver:5432/db"
        - name: BOARD_SIZE
          value: "4"
        ports:
        - containerPort: 8080
